### ISSUE TITLE
Ammo available at start?

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#14]

**Comment by Ataraxey2** [comment]
Wicked arrows/blackflight arrows, impact shot and ironbite shot all available in Honor Hold from the Innkeeper Sid Limbardi

Scryer/Aldor both have a unique vendor that sells all arrows/bullets from various TBC reps 
Scryer one here https://gyazo.com/6fe61642c688c62b78fa7a5c78fef26c
