### ISSUE TITLE
Melee swing timer vs ranged swing, and any delays?

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#15]

**Comment by watchyoursixx** [comment]
Tested myself and did not have any noticeable delays. Felt fluid and strong :)

**Comment by skinnay-dev** [comment]
Djlovedrop confirmed that Mend Pet, which is now an instant HoT, no longer resets swing timers as it does in Classic vanilla as a channeled ability.

Aimed shot now resets both melee and ranged swing timers.

Health potion still resets both melee and ranged swing timers as it does in Classic vanilla.

**Comment by skinnay-dev** [comment]
This clip from Bean shows that Steady Shot does not reset melee swing timer:

https://clips.twitch.tv/AuspiciousAuspiciousStapleDBstyle-5IaGDBnD9-jjNXBz

(The "tiny delay if I get the auto off" at the end appears to be the delay from pre-toggling Raptor strike before entering melee range that we're familiar with in Classic vanilla.)

**Comment by watchyoursixx** [comment]
From many of my tests I did not have delays directly related to melee/ranged swing timers interacting, but I did have some issues casting raptor immediately after a steady cast.

Delaying slightly after steady would still allow instant raptors in melee.
