### ISSUE TITLE
How do haste effects impact speeds of Steady, Auto, Multi and Aimed?

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#17]

**Comment by skinnay-dev** [comment]
According to this log from Sixx, Aimed Shot has a hidden 0.5 seconds of extra cast time, making it a 3.0 second base cast despite the tooltip stating 2.5 seconds. This behaves the same as Aimed Shot in Classic vanilla having a 3.0 tooltip + 0.5 second cast time. The 15% quiver haste is affecting the entire cast, bringing it down to ~2.61s, also shown in the log.

![](https://cdn.discordapp.com/attachments/794708239777923082/824048958577967164/unknown.png)

**Comment by watchyoursixx** [comment]
![image](https://user-images.githubusercontent.com/47162044/112595727-2d2cc980-8de1-11eb-81f3-b96aeb38fb1d.png)
Haste is as expected. Unsure how haste rating applies here (400 rating from pot) because I was lvl 62, but adjusting for level it gets pretty close to expected.

**Comment by watchyoursixx** [comment]
https://www.warcraftlogs.com/reports/6GpaF7Wnyhbj9Tv8/#fight=5&type=summary&view=events

More info on steady with varying speeds (quick shots, rapid fire, haste pot, BM, quiver, stacked together, each falling off individually except quiver and BM)

Steady Shot has 1.5 sec cast time (1 per tooltip + 0.5 hidden) affected by all haste.
Aimed Shot has 3.0 sec cast time (2.5 per tooltip + 0.5 hidden) affected by all haste.
Auto Shot (and Multi-Shot) will be assumed to behave the same as expected barring any sudden changes (0 + 0.5 hidden) affected by all haste.

**Comment by watchyoursixx** [comment]
Marking as confirmed behavior.
