### ISSUE TITLE
Can't dismiss pet, says invalid target

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#19]

**Comment by watchyoursixx** [comment]
![image](https://user-images.githubusercontent.com/47162044/112234697-70d1d880-8c13-11eb-94da-5b8caecd565b.png)

**Comment by Aggrend** [comment]
There is a fix for this coming real soon.

**Comment by watchyoursixx** [comment]
Fixed as of 4/6/21 build 38225
