### ISSUE TITLE
Auto shot is not automatically switching to enabled when leaving melee range per patch 2.0.1, also can't right click to start shooting

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#20]
Patch 2.0.1 noted that you should automatically switch to auto shot if leaving ranged combat.

I believe there was also a setting for this in the UI to toggle this off (I personally prefer it off)

**Comment by watchyoursixx** [comment]
![image](https://user-images.githubusercontent.com/47162044/112748785-33ab7480-8f8c-11eb-841d-7881f68684b2.png)
https://web.archive.org/web/20120127155651/http://us.battle.net/wow/en/game/patch-notes/2-0-1

**Comment by Aeded** [comment]
" Patch 2.1.0 (22-May-2007): Hunters now have a UI option Auto Attack/Auto Shot that if turned off means that the hunter will not automatically switch between ranged attack and melee attack difficulty when the range changes."

I checked if this just a missing interface option, but old cVar that was used for it doesnt exist either "autoRangedCombat"

**Comment by watchyoursixx** [comment]
Autos now switch between melee/range and you can right click to attack from range.

Still missing a UI option for it it looks like though.

**Comment by watchyoursixx** [comment]
Closing and opening a new issue for the UI thing
