### ISSUE TITLE
Focused Fire (Hunter talent) % bonus persists after talent respec

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#21]
No increased damage on tooltip or on actual damage done. Will link logs later from vod.

**Comment by watchyoursixx** [comment]
appears to be working now. Will double check vod to make sure I didn't mess up the initial test.. otherwise it was fixed today or yesterday's patches.

**Comment by watchyoursixx** [comment]
confirmed via my vod that it did not work correctly on day 1. Ty blizz <3

**Comment by watchyoursixx** [comment]
Found out today that this persists even after respeccing without it. So you keep the 2% bonus without even having it talented if you have talented it before.

**Comment by a17n** [comment]
It also works the other way around. If you have your pet active while you respecc into Focused Fire you don't get the additional 2% dmg until you dismiss and call pet again.

**Comment by watchyoursixx** [comment]
Normally your pet is dismissed when retalenting so I don't think I ever noticed this if it did it before

**Comment by watchyoursixx** [comment]
Appears fixed as of build 38364
