### ISSUE TITLE
The Beast Within does not work at all for the player

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#27]
![Screenshot 2021-03-23 225940](https://user-images.githubusercontent.com/47162044/112247950-80f5b200-8c2b-11eb-8e59-b490886c10cb.jpg)

**Comment by Aggrend** [comment]
There's a fix for this which should be on beta soon.

**Comment by watchyoursixx** [comment]
![image](https://user-images.githubusercontent.com/47162044/112908176-0c07f980-90bd-11eb-9c58-a693ee44118c.png)
fixed with latest build.
