### ISSUE TITLE
What consumables stack?

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#29]

**Comment by watchyoursixx** [comment]
it appears valentines +30 agi, battle elixir and scroll all stack together. Did not have food at the time to test as well.

**Comment by watchyoursixx** [comment]
seen some screenshots of all valentines candy stacking too.

**Comment by Ataraxey2** [comment]
Nightfin soup buff does not stack with any other food buffs (vanilla or TBC), seen some videos saying it does but they are wrong.

% food + AV food still stacks for double regen, mana at least (unsure hp)

All valentines chocolates stack + stack with food buff, + stat valentines buff, battle/guardian elixir and scroll

**Comment by watchyoursixx** [comment]
To summarize:

Scrolls stack with any non-single stat buff. 
Battle elixirs and guardian elixirs stack with scrolls.
All chocolates from valentines stack.
Food buffs stack with everything, but not each other. Alcoholic drinks count as food.
Stat valentines buff (+30 agi for example) stack with everything
