### ISSUE TITLE
Auto shot not displaying cast start or success in combat log, even though it has a cast time

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#30]
important for hunters to be able to watch their swing timer accurately, without the actual cast time data we can't time rotations efficiently.

**Comment by raethkcj** [comment]
It never has, try these:

https://wowpedia.fandom.com/wiki/UNIT_SPELLCAST_START
https://wowpedia.fandom.com/wiki/UNIT_SPELLCAST_SUCCEEDED

**Comment by watchyoursixx** [comment]
It actually always has, so not sure what you're referring to. This isn't retail.

Classic auto shot has always had a start cast and cast success just like any other spell in the combat log. Just go look at any classic wcl for hunters.

Now it only says "range damage" which means it's behaving like a "melee" because it's not showing a cast, even though it still has the inherent 0.5 sec cast reduced by haste. This tiny cast wasn't removed until cata when you were able to shoot while moving.

Both of those return nothing for auto shot also, but they should work

**Comment by mechanicsTBC** [comment]
yes this is a major issue, hunters gain a large amount of additional auto shots that they shouldn't, especially during haste effects.

https://github.com/SunstriderEmu/BugTracker/issues/224
https://wow.allakhazam.com/wiki/shot_rotation_(WoW)
for reference

**Comment by watchyoursixx** [comment]
Neither of those have anything to do with what I'm referencing here... But also, one is pserver info and another is from an outdated "theorycraft" that didn't understand the actual game mechanics with regards to auto shot, since it was pretty hard to interpret back then.

We know from classic that auto shot has a 0.5 sec cast time, reduced by haste. This also works in the same manner in TBC, and did not change throughout TBC (just go watch any vid in slow motion and you'll see haste makes the auto "cast" faster than 0.5s like everyone claimed it was.

Not sure how any of this has to do with "gaining a large amount of additional autos" without really explaining what you mean by "shouldn't". Haste makes autos go faster, and same is true here in BCC. That's true for any version of WoW.

**Comment by watchyoursixx** [comment]
fixed as of build 38285
