### ISSUE TITLE
Does Steady shot suffer casting pushback from damage taken? Does Aimed shot still?

### ISSUE THREAD

**Issue by skinnay-dev** [watchyoursixx/hunter-tbc#31]

**Comment by watchyoursixx** [comment]
Both spells suffer spell pushback.

The closest I could determine from classic was + 1 sec on first hit and 0.2 per hit each successive hit after, with the first 1 sec of a cast giving a proportionate reduction in the first hit based on current time of cast.

Examples: 
Casting ability at 2 sec cast time, hit 1 time after 1 sec into cast, total cast time 3 sec.
Casting ability at 2 sec cast time, hit twice after 1 sec into cast, total cast time 3.2 sec.
Casting ability at 2 sec cast time, hit once at 0.5 sec into cast, total cast time 2.5 sec.
Casting ability at 2 sec cast time, hit twice; once at 0.5 sec into cast and once at 1.5 sec, total cast time 2.7 sec.

**Comment by watchyoursixx** [comment]
https://classic.warcraftlogs.com/reports/hXpkCQPdBy3KDqxt#fight=9&type=casts&view=timeline&source=2
example of steady w/ pushback, hit at 26.667:
![image](https://user-images.githubusercontent.com/47162044/112597904-2d7a9400-8de4-11eb-8f93-3b3a83e7617c.png)

Total cast time with 1.15 quiver and 1.2 BM:
Expected - 1.5 / 1.15 / 1.2 = 1.087~
Actual - 25.717 to 27.767 = 2.05 total time, added time = 26.667 - 25.717 or 0.95~, 0.95 + 1.087 = 2.0367~ or with server ticks and some rounding, 2.05~
