### ISSUE TITLE
Flare persists on the target for several seconds after the target leaves the flared area (4-6 sec)

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#33]
Can add example later, stream not working atm.

**Comment by ajames27** [comment]
I think this is the current behavior in classic. Two things I'm curious about, does it affect other aura area of effect spells like trap effects and does entering the effect versus having it cast on you affect how long it takes to fall off?

**Comment by watchyoursixx** [comment]
https://streamable.com/e2xq7v example of flare persisting for a significant distance/time

**Comment by Vorean** [comment]
I don’t think this is a bug, as flare always applies a debuff to the enemy, so they can’t run out of range and vanish or stealth again. I recall this being a timed debuff on my rogue  partner back in TBC.

it’s also how it worked in Classic.

**Comment by watchyoursixx** [comment]
Funny you comment on this, but I was actually closing it as this has been fixed. It's now consistently 1-3 sec like it was in classic.

Closing this as of the prepatch build 38709
