### ISSUE TITLE
Pet cobra reflexes and avoidance are not available from the pet trainer. 

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#37]
No trainer appears to train these. Should be learnable at level 30 for rank 1 avoidance, cobra reflexes, and level 60 for rank 2 avoidance. Not sure if there's another one but these are the ones I remember.

**Comment by Aggrend** [comment]
This was an issue with the pet trainer missing all trainable skills. This should be resolved in the build next week (week of 4/5)

**Comment by watchyoursixx** [comment]
Trainable and working as expected as of 4/6/21 build 38225. Thanks!
