### ISSUE TITLE
Do drums and Bloodlust/Heroism reduce GCD?

### ISSUE THREAD

**Issue by MarkNoordraven** [watchyoursixx/hunter-tbc#38]

**Comment by watchyoursixx** [comment]
Unlikely to affect hunter's GCD because nothing else does, but we will confirm it.

**Comment by watchyoursixx** [comment]
![image](https://user-images.githubusercontent.com/47162044/114247258-aa6c4880-9962-11eb-9729-e023628f1366.png)
tested bloodlust with GCD and did not have any reduction with several damaging spells.
https://www.warcraftlogs.com/reports/VyMZPBN2DJbRWhFw/#fight=last&type=summary&source=1&view=events
