### ISSUE TITLE
Only 1 pet gains greater blessings, instead of all pets

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#4]

**Comment by Dasharius** [comment]
Keeping it in line with original TBC:

Hunter Pets and Felguards are classified as warrior and should be affected by Greater Blessings on the Warriors.
All other Warlock Pets should be considered as Warlock.

Weak evidence of that is provided here: https://www.wowhead.com/forums/topic/29070

But I don't have Beta access. Just stating that the question itself is "wrong"

**Comment by watchyoursixx** [comment]
Pets are currently in their own category, but can actually be buffed by greater blessing. 
https://clips.twitch.tv/HealthyTameBobaYee-A1TkYEqaLeyeA0pt

**Comment by watchyoursixx** [comment]
Confirmed on beta that pets are currently not getting greater blessing when buffing "pets" as a whole, but individually can be buffed by greater blessing. Will add link to clip from stream later.

**Comment by watchyoursixx** [comment]
https://clips.twitch.tv/SmoothRamshackleWaterPupper-dqbothzu1ulmZufI

**Comment by watchyoursixx** [comment]
pets finally got the warrior treatment in p3 marking as closed
