### ISSUE TITLE
Hunter pets chase targets that enter stealth after the pet was sent to attack.

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#44]
Per patch 2.2 bug fixes, hunter pets will no longer chase targets that vanish. (tried linking original patch notes but couldn't find them on waybackmachine)
![image](https://user-images.githubusercontent.com/47162044/112769521-908c4680-8fef-11eb-8572-0755a05bd57b.png)

**Comment by Klimpb** [comment]
Note that pets shouldn't chase players that stealth or shadowmeld either.
Undocumented fix in last patch of tbc.

Source:
http://web.archive.org/web/20160419071550/http://www.arenajunkies.com/topic/31486-shadowmeld-calling-back-pets-solution/
http://web.archive.org/web/20190801092046/http://www.arenajunkies.com/topic/29172-hidden-hunter-nerfbug-fix-in-243/page-2

Can be seen here: https://www.youtube.com/watch?v=D_iQHXtod6Y&t=1246s

**Comment by watchyoursixx** [comment]
Pets no longer chase vanished targets on aggressive or passive, but still chase targets that stealth while already commanded to attack.

**Comment by watchyoursixx** [comment]
To add to this: Pets follow their target, but do not attack in this scenario.

**Comment by Aggrend** [comment]
This was fixed this match reference. Hunter pets will continue to follow, but not attack stealthed targets. They should not, however, chase vanished targets (and no longer do according to internal testing and comments here). Going to call this fixed for now.

**Comment by watchyoursixx** [comment]
Making as closed per the above.
