### ISSUE TITLE
Debuff Application Dazes in Aspect of the Cheetah

### ISSUE THREAD

**Issue by BradBlondebeard** [watchyoursixx/hunter-tbc#64]
On TBC Beta debuff application dazes you in Aspect of the Cheetah. In Classic debuff application does not daze in Aspect of the Cheetah. Example clip: https://clips.twitch.tv/PopularDeterminedSrirachaKappa-Yfr5BXbhFQ-LE8d- Hunter takes no damage, but Cripple dazes the hunter.

**Comment by watchyoursixx** [comment]
This is just one example. It appears any debuff will daze the hunter as well as somehow just attacking a dummy dazes the hunter with cheetah active (only instant damaging abilities should daze).

**Comment by watchyoursixx** [comment]
fixed as of 38709
