### ISSUE TITLE
Elixir of Demonslaying RAP?

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#8]

**Comment by HunterNewt** [comment]
Limited sample of level 58 Starving Helboars using only Auto Shot.

With Elixir of Demonslaying
https://classic.warcraftlogs.com/reports/gpQWMAV6JHF842KB#boss=-3&difficulty=0&type=damage-done&source=3&ability=75&target=2&view=events

Without Elixir of Demonslaying
https://classic.warcraftlogs.com/reports/CA31pQhTaKVJ2Rwj/#boss=-3&difficulty=0&source=1&type=damage-done&target=3&ability=75&view=events

**Comment by watchyoursixx** [comment]
@HunterNewt can you test again with https://classic.wowhead.com/item=15808/fine-light-crossbow

**Comment by HunterNewt** [comment]
@watchyoursixx Here you go a little test with Lv60 Forge Camp Legionnaires.
There may have been a Ferocious Inspiration here and there, but you get the picture.

With
https://classic.warcraftlogs.com/reports/kZVy8YmFGMaRQjwd#boss=-3&difficulty=0&type=damage-done&source=1&target=2&ability=75&view=events

Without
https://classic.warcraftlogs.com/reports/MX1xVHFBZfCj7Pvc/#boss=-3&difficulty=0&type=damage-done&source=1&target=3&ability=75&view=events

**Comment by watchyoursixx** [comment]
Okay good. Does pet also benefit from this? I would think so but maybe not

**Comment by HunterNewt** [comment]
Lv63 Owl with auto attacks only vs. the same mobs from before. Doesn't seem to be any difference.

With
https://classic.warcraftlogs.com/reports/gLQcnZjaM72HPmpb/#boss=-3&difficulty=0&type=damage-done&source=1&ability=1&view=events&target=3

Without
https://classic.warcraftlogs.com/reports/PrpJDkV4hYzNmc2Q/#boss=-3&difficulty=0&source=2&type=damage-done&target=3&ability=1&view=events

**Comment by watchyoursixx** [comment]
Okay so based on this and the other tests with MotC, we can assume pet does not get AP from specific target types. This kinda makes sense because pets don't benefit from Hunter's mark RAP or from expose weakness RAP (from the hunter) and I'd assume the AP per target type is being applied in the same way "like a debuff" rather than re-calculating the hunter's RAP based on what it's targeting it only calculates it when the target is attacked. So pet would not be able to benefit from it since it's not a bonus to your RAP always, just at the moment you attack a specific type.
